name: flutter_oss_aliyun
description: oss aliyun plugin for flutter and upport STS to access OSS temporarily
version: 6.2.3
repository: https://github.com/huhx/flutter_oss_aliyun

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dio: ^5.0.0
  async: ^2.9.0
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  
flutter:
